nelmio_cors:
    defaults:
        allow_origin: []
        allow_methods: []
        allow_headers: []
        expose_headers: []
        max_age: 0
        allow_credentials: false
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600